from __future__ import annotations

import json

from sqlalchemy.orm import Session

from app.models import FieldDefinition, FieldResponsibility, Role
from app.models.enums import Responsibility

# Format:
# key, section, label, help_text, input_type, enum_values, is_required,
# conditional_on_key, conditional_equals
# responsibilities: {"F": [role_codes], "I": [role_codes]}

FIELD_DEFS = [
    {
        "key": "stammdaten.application_owner",
        "section": "STAMMDATEN",
        "label": "Application Owner (fachlich)",
        "help_text": "Fachlich verantwortliche Person für die Anwendung.",
        "input_type": "ENUM",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 1,
        "F": ["APP_MANAGER"],
        "I": ["BETRIEBSRAT", "IT_SECURITY", "DATA_PROTECTION", "APP_OPERATION", "LICENSE_MGMT"],
    },
    {
        "key": "stammdaten.it_application_owner",
        "section": "STAMMDATEN",
        "label": "IT Application Owner (technisch)",
        "help_text": "Technisch verantwortliche Person aus der IT.",
        "input_type": "ENUM",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 2,
        "F": ["APP_OPERATION"],
        "I": ["BETRIEBSRAT", "IT_SECURITY", "DATA_PROTECTION", "APP_MANAGER", "LICENSE_MGMT"],
    },
    {
        "key": "stammdaten.bit_fc",
        "section": "STAMMDATEN",
        "label": "Betroffene BIT-/FC-Kategorie",
        "help_text": "Zuordnung zur Business-IT- bzw. Fachbereichs-Kategorie (Multi-Select).",
        "input_type": "ENUM_MULTI",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 3,
        "F": ["APP_MANAGER"],
        "I": ["BETRIEBSRAT", "IT_SECURITY", "DATA_PROTECTION", "APP_OPERATION", "LICENSE_MGMT"],
    },
    {
        "key": "stammdaten.short_description",
        "section": "STAMMDATEN",
        "label": "Kurzbeschreibung",
        "help_text": "Kurzbeschreibung der Anwendung als Tagline (max. 280 Zeichen).",
        "input_type": "TEXT",
        "enum_values": None,
        "is_required": False,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 4,
        "F": ["APP_MANAGER"],
        "I": ["BETRIEBSRAT", "IT_SECURITY", "DATA_PROTECTION", "APP_OPERATION", "LICENSE_MGMT"],
    },
    {
        "key": "stammdaten.installation_location",
        "section": "STAMMDATEN",
        "label": "Wo wird die Software installiert?",
        "help_text": "Installationsort: amedes-RZ, Cloud-Region, Endgerät, etc.",
        "input_type": "TEXT",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 5,
        "F": ["IT_SECURITY", "APP_OPERATION"],
        "I": ["BETRIEBSRAT", "DATA_PROTECTION", "APP_MANAGER", "LICENSE_MGMT"],
    },
    {
        "key": "system_category.code",
        "section": "KATEGORIE",
        "label": "Systemkategorie (A/B/C/D)",
        "help_text": "Mitbestimmungsrelevanz-Kategorie nach amedes-Bewertungsschema.",
        "input_type": "ENUM",
        "enum_values": json.dumps(["A", "B", "C", "D"]),
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 6,
        "F": ["BETRIEBSRAT"],
        "I": ["IT_SECURITY", "DATA_PROTECTION", "APP_MANAGER", "APP_OPERATION", "LICENSE_MGMT"],
    },
    {
        "key": "system_category.justification",
        "section": "KATEGORIE",
        "label": "Begründung Systemkategorie",
        "help_text": "Pflicht bei Kategorie D: Begründung für den Notfall-Workflow.",
        "input_type": "LONGTEXT",
        "enum_values": None,
        "is_required": False,
        "conditional_on_key": "system_category.code",
        "conditional_equals": "D",
        "sort_order": 7,
        "F": ["BETRIEBSRAT", "APP_MANAGER", "APP_OPERATION"],
        "I": ["IT_SECURITY", "DATA_PROTECTION", "LICENSE_MGMT"],
    },
    {
        "key": "produkt.hersteller",
        "section": "PRODUKT",
        "label": "Hersteller",
        "help_text": "Name des Software-Herstellers oder Lieferanten.",
        "input_type": "TEXT",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 8,
        "F": ["LICENSE_MGMT", "APP_MANAGER"],
        "I": ["BETRIEBSRAT", "IT_SECURITY", "DATA_PROTECTION", "APP_OPERATION"],
    },
    {
        "key": "produkt.name",
        "section": "PRODUKT",
        "label": "Produktname",
        "help_text": "Offizieller Produktname der Software.",
        "input_type": "TEXT",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 9,
        "F": ["APP_MANAGER"],
        "I": ["BETRIEBSRAT", "IT_SECURITY", "DATA_PROTECTION", "APP_OPERATION", "LICENSE_MGMT"],
    },
    {
        "key": "produkt.version",
        "section": "PRODUKT",
        "label": "Version",
        "help_text": "Versionsnummer der einzuführenden Software.",
        "input_type": "TEXT",
        "enum_values": None,
        "is_required": False,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 10,
        "F": ["APP_OPERATION"],
        "I": ["BETRIEBSRAT", "IT_SECURITY", "DATA_PROTECTION", "APP_MANAGER", "LICENSE_MGMT"],
    },
    {
        "key": "produkt.beschreibung",
        "section": "PRODUKT",
        "label": "Systembeschreibung",
        "help_text": "Was ist die Software? (nicht: wie wird sie genutzt?)",
        "input_type": "LONGTEXT",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 11,
        "F": ["APP_MANAGER"],
        "I": ["BETRIEBSRAT", "IT_SECURITY", "DATA_PROTECTION", "APP_OPERATION", "LICENSE_MGMT"],
    },
    {
        "key": "projekt.einfuehrungszeitpunkt",
        "section": "PROJEKT",
        "label": "Einführungszeitpunkt",
        "help_text": "Geplantes Datum der produktiven Einführung.",
        "input_type": "DATE",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 12,
        "F": ["APP_MANAGER", "APP_OPERATION"],
        "I": ["BETRIEBSRAT", "IT_SECURITY", "DATA_PROTECTION", "LICENSE_MGMT"],
    },
    {
        "key": "projekt.standorte",
        "section": "PROJEKT",
        "label": "Auszurollende Standorte",
        "help_text": "An welchen Standorten wird die Software eingesetzt?",
        "input_type": "LONGTEXT",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 13,
        "F": ["APP_MANAGER"],
        "I": ["BETRIEBSRAT", "IT_SECURITY", "DATA_PROTECTION", "APP_OPERATION", "LICENSE_MGMT"],
    },
    {
        "key": "anwendung.zweck",
        "section": "ANWENDUNG",
        "label": "Zweck der Anwendung",
        "help_text": "Wofür wird das System bei amedes genutzt – und was ändert sich dadurch im Alltag?",
        "input_type": "LONGTEXT",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 14,
        "F": ["APP_MANAGER"],
        "I": ["BETRIEBSRAT", "IT_SECURITY", "DATA_PROTECTION", "APP_OPERATION", "LICENSE_MGMT"],
    },
    {
        "key": "anwendung.betroffene_personen",
        "section": "ANWENDUNG",
        "label": "Betroffene Personen",
        "help_text": "Wer ist betroffen? (Mitarbeitende, Patienten, Externe)",
        "input_type": "LONGTEXT",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 15,
        "F": ["DATA_PROTECTION", "BETRIEBSRAT"],
        "I": ["IT_SECURITY", "APP_MANAGER", "APP_OPERATION", "LICENSE_MGMT"],
    },
    {
        "key": "anwendung.rechtemanagement",
        "section": "ANWENDUNG",
        "label": "Rechtemanagement",
        "help_text": "Wie werden Zugriffsrechte vergeben? (Rollen, Gruppen, AD-Anbindung?)",
        "input_type": "LONGTEXT",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 16,
        "F": ["IT_SECURITY"],
        "I": ["BETRIEBSRAT", "DATA_PROTECTION", "APP_MANAGER", "APP_OPERATION", "LICENSE_MGMT"],
    },
    {
        "key": "anwendung.leistungsueberwachung",
        "section": "ANWENDUNG",
        "label": "Eignung zur Leistungsüberwachung",
        "help_text": (
            "Kann das System Leistung/Verhalten von Mitarbeitenden überwachen? "
            "Wenn ja: wie wird Missbrauch verhindert?"
        ),
        "input_type": "YESNO",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 17,
        "F": ["BETRIEBSRAT"],
        "I": ["IT_SECURITY", "DATA_PROTECTION", "APP_MANAGER", "APP_OPERATION", "LICENSE_MGMT"],
    },
    {
        "key": "schnittstellen.umsysteme",
        "section": "SCHNITTSTELLEN",
        "label": "Schnittstellen zu Umsystemen",
        "help_text": "Welche Schnittstellen gibt es zu welchen Systemen – mit welchen Daten?",
        "input_type": "LONGTEXT",
        "enum_values": None,
        "is_required": False,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 18,
        "F": ["IT_SECURITY", "APP_OPERATION"],
        "I": ["BETRIEBSRAT", "DATA_PROTECTION", "APP_MANAGER", "LICENSE_MGMT"],
    },
    {
        "key": "datenschutz.personenbezogen",
        "section": "DATENSCHUTZ",
        "label": "Personenbezogene Daten",
        "help_text": "Werden personenbezogene Daten verarbeitet? (Ja/Nein)",
        "input_type": "YESNO",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 19,
        "F": ["DATA_PROTECTION"],
        "I": ["BETRIEBSRAT", "IT_SECURITY", "APP_MANAGER", "APP_OPERATION", "LICENSE_MGMT"],
    },
    {
        "key": "datenschutz.rechtsgrundlage",
        "section": "DATENSCHUTZ",
        "label": "Rechtsgrundlage der Verarbeitung",
        "help_text": "Rechtsgrundlage gem. DSGVO Art. 6 (nur wenn personenbezogene Daten: ja).",
        "input_type": "LONGTEXT",
        "enum_values": None,
        "is_required": False,
        "conditional_on_key": "datenschutz.personenbezogen",
        "conditional_equals": "ja",
        "sort_order": 20,
        "F": ["DATA_PROTECTION"],
        "I": ["BETRIEBSRAT", "IT_SECURITY", "APP_MANAGER", "APP_OPERATION", "LICENSE_MGMT"],
    },
    {
        "key": "datenschutz.dpia_erforderlich",
        "section": "DATENSCHUTZ",
        "label": "Datenschutz-Folgenabschätzung (DPIA) erforderlich?",
        "help_text": "DPIA gem. DSGVO Art. 35 erforderlich? (nur wenn personenbezogene Daten: ja)",
        "input_type": "YESNO",
        "enum_values": None,
        "is_required": False,
        "conditional_on_key": "datenschutz.personenbezogen",
        "conditional_equals": "ja",
        "sort_order": 21,
        "F": ["DATA_PROTECTION"],
        "I": ["BETRIEBSRAT", "IT_SECURITY", "APP_MANAGER", "APP_OPERATION", "LICENSE_MGMT"],
    },
    {
        "key": "lizenzen.modell",
        "section": "LIZENZEN",
        "label": "Lizenzmodell",
        "help_text": "Welches Lizenzmodell gilt? (PerUser, PerCore, Site, Open)",
        "input_type": "ENUM",
        "enum_values": json.dumps(["PerUser", "PerCore", "Site", "Open"]),
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 22,
        "F": ["LICENSE_MGMT"],
        "I": ["BETRIEBSRAT", "IT_SECURITY", "DATA_PROTECTION", "APP_MANAGER", "APP_OPERATION"],
    },
    {
        "key": "lizenzen.anzahl",
        "section": "LIZENZEN",
        "label": "Anzahl Lizenzen",
        "help_text": "Benötigte Anzahl an Lizenzen.",
        "input_type": "NUMBER",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 23,
        "F": ["LICENSE_MGMT"],
        "I": ["APP_MANAGER"],
    },
    {
        "key": "betrieb.amedes_it_verantwortung",
        "section": "BETRIEB",
        "label": "amedes IT-Betriebsverantwortung",
        "help_text": "Was übernimmt die amedes-IT im Betrieb (Updates, Backup, Monitoring, …)?",
        "input_type": "LONGTEXT",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 24,
        "F": ["APP_OPERATION"],
        "I": ["BETRIEBSRAT", "IT_SECURITY", "DATA_PROTECTION", "APP_MANAGER", "LICENSE_MGMT"],
    },
    {
        "key": "betrieb.backup_strategie",
        "section": "BETRIEB",
        "label": "Backup-Strategie",
        "help_text": "Wie werden Daten gesichert und wiederhergestellt?",
        "input_type": "LONGTEXT",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 25,
        "F": ["APP_OPERATION", "IT_SECURITY"],
        "I": ["BETRIEBSRAT", "DATA_PROTECTION", "APP_MANAGER", "LICENSE_MGMT"],
    },
    {
        "key": "cloud.cloudbasiert",
        "section": "CLOUD",
        "label": "Cloudbasiertes System?",
        "help_text": "Wird das System über Internet/Cloud bereitgestellt? (Ja/Nein)",
        "input_type": "YESNO",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 26,
        "F": ["IT_SECURITY", "DATA_PROTECTION"],
        "I": ["BETRIEBSRAT", "APP_MANAGER", "APP_OPERATION", "LICENSE_MGMT"],
    },
    {
        "key": "cloud.region",
        "section": "CLOUD",
        "label": "Cloud-Region",
        "help_text": "In welcher Region/welchem Rechenzentrum werden Daten verarbeitet?",
        "input_type": "TEXT",
        "enum_values": None,
        "is_required": False,
        "conditional_on_key": "cloud.cloudbasiert",
        "conditional_equals": "ja",
        "sort_order": 27,
        "F": ["IT_SECURITY", "DATA_PROTECTION"],
        "I": ["APP_OPERATION"],
    },
    {
        "key": "sla.verfuegbarkeit",
        "section": "SLA",
        "label": "Verfügbarkeit (SLA)",
        "help_text": "Vereinbarte Verfügbarkeit in % (z. B. 99,5 %).",
        "input_type": "TEXT",
        "enum_values": None,
        "is_required": True,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 28,
        "F": ["APP_OPERATION"],
        "I": ["APP_MANAGER", "LICENSE_MGMT"],
    },
    {
        "key": "kosten.einmalig",
        "section": "KOSTEN",
        "label": "Einmalige Kosten (€)",
        "help_text": "Einmalige Anschaffungs-/Implementierungskosten in Euro.",
        "input_type": "NUMBER",
        "enum_values": None,
        "is_required": False,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 29,
        "F": ["LICENSE_MGMT"],
        "I": ["APP_MANAGER"],
    },
    {
        "key": "sonstiges.anmerkungen",
        "section": "SONSTIGES",
        "label": "Sonstige Anmerkungen",
        "help_text": "Anmerkungen oder Risiken, die sonst nicht erfasst sind?",
        "input_type": "LONGTEXT",
        "enum_values": None,
        "is_required": False,
        "conditional_on_key": None,
        "conditional_equals": None,
        "sort_order": 30,
        "F": [],  # No approval responsibility
        "I": ["BETRIEBSRAT", "IT_SECURITY", "DATA_PROTECTION", "APP_MANAGER", "APP_OPERATION", "LICENSE_MGMT"],
    },
]


def seed_fields(session: Session) -> None:
    for data in FIELD_DEFS:
        field = (
            session.query(FieldDefinition).filter(FieldDefinition.key == data["key"]).first()
        )
        if not field:
            field = FieldDefinition(
                key=data["key"],
                section=data["section"],
                label=data["label"],
                help_text=data["help_text"],
                input_type=data["input_type"],
                enum_values=data["enum_values"],
                is_required=data["is_required"],
                conditional_on_key=data["conditional_on_key"],
                conditional_equals=data["conditional_equals"],
                sort_order=data["sort_order"],
            )
            session.add(field)
            session.flush()

        # Seed responsibilities
        existing_resp = {
            (r.role_id,)
            for r in session.query(FieldResponsibility)
            .filter(FieldResponsibility.field_id == field.id)
            .all()
        }

        for role_code in data["F"]:
            role = session.query(Role).filter(Role.code == role_code).first()
            if role and (role.id,) not in existing_resp:
                session.add(
                    FieldResponsibility(
                        field_id=field.id,
                        role_id=role.id,
                        kind=Responsibility.APPROVAL.value,
                    )
                )

        for role_code in data["I"]:
            role = session.query(Role).filter(Role.code == role_code).first()
            if role and (role.id,) not in existing_resp:
                session.add(
                    FieldResponsibility(
                        field_id=field.id,
                        role_id=role.id,
                        kind=Responsibility.INFO.value,
                    )
                )

        session.flush()
